#!/bin/bash
yum update -y

# Install Docker
yum install -y docker
systemctl start docker
systemctl enable docker
usermod -aG docker ec2-user

# Install AWS CLI
yum install -y aws-cli

# Login to ECR
aws ecr get-login-password --region us-east-1 \
| docker login --username AWS \
--password-stdin 890608336810.dkr.ecr.us-east-1.amazonaws.com

# Pull Docker image
docker pull 890608336810.dkr.ecr.us-east-1.amazonaws.com/ml-api:latest

# Run container
docker run -d -p 8000:8000 \
890608336810.dkr.ecr.us-east-1.amazonaws.com/ml-api:latest
cd /home/ec2-user
mkdir suvendu